version: 0.2

env:
  variables:
    AWS_REGION: "region"
    BUCKET_NAME: "bucket"
    CDN_DISTRIBUTION_ID: "id"
    TARGET_ACCOUNT_ID: "id"

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip3 install awscli --upgrade --user
      - echo `aws --version`
      - pip3 install Pygments

      - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
      - dpkg -i hugo_0.53_Linux-64bit.deb

      - echo Switching to CodeBuild role in other account...
      - eval $(aws sts assume-role --role-arn arn:aws:iam::$TARGET_ACCOUNT_ID:role/codebuild-role --role-session-name codebuild-session | jq -r '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) "')
      - echo Confirming new role...
      - aws sts get-caller-identity
  build:
    commands:
      - echo Build started on `date`
      - hugo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying to S3 bucket...
      - aws s3 sync --delete public/ s3://$BUCKET_NAME/ --cache-control max-age=86400
      - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
