version: 0.2

env:
  variables:
    BUCKET_NAME: "bucket"

phases:
  install:
    commands:
      - pip install Pygments
      - wget https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.deb
      - dpkg -i hugo_0.47.1_Linux-64bit.deb
  build:
    commands:
      - echo Build started on `date`
      - hugo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying to S3 bucket...
      - aws s3 sync --delete public/ s3://$BUCKET_NAME/ --cache-control max-age=60
