title = "Charles Sieg"
#baseURL = "https://staging.charlessieg.com/"
languageCode = "en-us"
theme = "accelastudy"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/charles.sieg"
  twitter = "https://www.twitter.com/charlessieg"
  instagram = "https://www.instagram.com/charlessieg"
  youtube = ""
  github = "https://github.com/CharlesSieg"
  linkedin = "https://www.linkedin.com/in/charlessieg"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 10
